- README.md
added my name, photo, and github profile to readme
> Adding myself to readme

- .overcommit.yml
- .rubocop.yml
- Gemfile
- Gemfile.lock
- Set up Rubocop and Overcommit for strict linting on pre-commits
- Commit won't fail on linting error yet, but I'll likely set up a Travis rubocop check later
> Set up strict Rubocop linting

- .rubocop.yml
- Gemfile
- Gemfile.lock
- config/database.yml
- db/schema.rb
- Switch from sqlite3 to postgres and do very preliminary setup
- 
- 
This resolves issue #13.
> Add Postgres setup

- .github/PULL_REQUEST_TEMPLATE.md
> Add an attached issue section to PR template

- app/models/post.rb
- db/migrate/20191024025342_add_title_to_posts.rb
- db/schema.rb
- spec/factories/posts.rb
- spec/models/post_spec.rb
- Adds title field to Post of type string
- I assume posts will have a title and an optional body?
> Add title to Post model

- .ebextensions/00_options.config
- .ebextensions/01_install_dependencies.config
- .ebextensions/10_nginx_add_packs.config
- Gemfile
- Gemfile.lock
- config/database.yml
- Followed steps 1 - 4 as outlined here: https://piazza.com/class/k0wl5njhn3y45c?cid=47
Consider checking if on production / development instead for ruby gemfile install
related to issue 16, but may not be full solution yet.
> following instructions to deploy to aws

- app/views/posts/new.html.erb
- app/views/react_hello/index.html.erb
> Fixed link to log in

- app/views/posts/index.html.erb
> added sign out link

- app/assets/stylesheets/pages.scss
- app/controllers/comments_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/posts_controller.rb
- app/helpers/pages_helper.rb
- app/views/pages/home.html.erb
- app/views/posts/index.html.erb
- app/views/posts/new.html.erb
- app/views/posts/show.html.erb
- app/views/shared/_header.html.erb
- config/routes.rb
- spec/controllers/pages_controller_spec.rb
- spec/helpers/pages_helper_spec.rb
- Add better login checks
- Add landing page
- Add shared header and (not working) sign out button
- Add new post button and back button
- Cleaned up frontend (.erb) code
- No tests yet :(
Resolves #31
Resolves #32 
Resolves #36 
Resolves #37
> Link current frontend parts together and clean up code

- app/views/posts/index.html.erb
- load_test/load_test.xml
- load_test/simple.xml
> added tsung files

- Gemfile
- Gemfile.lock
- app/controllers/comments_controller.rb
- app/controllers/posts_controller.rb
- app/models/comment.rb
- app/models/post.rb
- app/models/user.rb
- app/views/posts/index.html.erb
- app/views/posts/show.html.erb
- config/routes.rb
- db/migrate/20191101225406_acts_as_votable_migration.rb
- db/schema.rb
- added gem 'acts_as_votable'
- added acts_as_votable to post and comment and acts_as_voter to user
- added routes to toggle a users like on a comment or post
- added simple toggle button on full post view to toggle like
#28
> adding spice functionality

- app/assets/javascripts/application.js
- app/assets/javascripts/posts.js
- app/controllers/posts_controller.rb
- app/views/layouts/application.html.erb
- app/views/posts/new.html.erb
- app/views/posts/new.js.erb
- See title
- Left IP geolocation in as fallback, we should decide how to utilize it later
- HTML5 geolocation for index is coming later
#46
> Add HTML5 Geolocation for new post

- app/assets/javascripts/html5loc_ajax.js
- app/assets/javascripts/html5loc_form.js
- See title
- Also fixes a bug where update_location would be called on /posts/new
-
> Change form js to AJAX

- app/assets/javascripts/application.js
- app/assets/javascripts/html5loc_ajax.js
- app/assets/javascripts/html5loc_form.js
- app/assets/javascripts/html5loc_shared.js
- Generates random stub coordinate if HTML5 geolocation fails
- Currently appears in a bounding box around LA-ish
-
Resolves #56
> Stub geolocation

- app/assets/stylesheets/profiles.scss
- app/controllers/profiles_controller.rb
- app/helpers/profiles_helper.rb
- app/views/profiles/profile.html.erb
- app/views/shared/_header.html.erb
- config/routes.rb
- spec/controllers/profiles_controller_spec.rb
- spec/helpers/profiles_helper_spec.rb
- Backend changes only; frontend is blank rn
- But the @user object is available :)
-
#59
> Add profile page (backend)

- Gemfile
- app/views/posts/index.html.erb
- app/views/posts/new.html.erb
- config/environments/development.rb
- Only allow images to be uploaded to posts
- Change dev to use local storage (and keep S3 as prod-only)
- Move location fields + js function calls to within the user-logged-in check
- Formatting
Resolves #66
> Fix image validation + small login ERB changes

- app/views/posts/show.html.erb
- A like check was put outside of `user_signed_in?` which caused the page to error when not signed in.
- Also a `.nil?` check was accidentally used instead of `.blank?` which caused `Comments...` to show up every time instead of `No comments`
-
> Fix image + user logged in bug

- app/assets/javascripts/application.js
- app/assets/stylesheets/spiciest.scss
- app/controllers/posts_controller.rb
- app/controllers/profiles_controller.rb
- app/controllers/spiciest_controller.rb
- app/helpers/spiciest_helper.rb
- app/models/post.rb
- app/views/posts/update_location.js.erb
- app/views/shared/_header.html.erb
- app/views/spiciest/spiciest.html.erb
- config/routes.rb
- spec/controllers/spiciest_controller_spec.rb
- spec/helpers/spiciest_helper_spec.rb
- See title (currently top 50 all time, subject to change e.g. adding top 50 daily)
- This relies on the `likes` field in Post, which isn't used until #71 
- Fix a few bugs relating to partial rendering and spice summing
- Move some ActiveRecord stuff to scopes
Resolves #70 (disregarding checks on the show method)
> Add spiciest posts page

- app/views/shared/_postcard.html.erb
- "comment" when 1 comment, "comments" otherwise
- It was bugging me :(
-
> Comment vs comments

- Gemfile
- Gemfile.lock
- app/controllers/posts_controller.rb
- app/controllers/react_hello_controller.rb
- app/javascript/packs/application.js
- app/javascript/packs/server_rendering.js
- app/views/layouts/application.html.erb
- app/views/react_hello/index.html.erb
- babel.config.js
- config/environments/development.rb
- config/routes.rb
- config/webpacker.yml
- package.json
- yarn.lock
- Remove React code (unfortunately this closes #30)
- Remove IP geolocation due to stubs in JS
-
> Delete now-unnecessary code

- .ebextensions/11_seed_database.config
> Fix EB seeding

- .ebextensions/11_seed_database.config
> More EB fixes

- .ebextensions/11_seed_database.config
> eb number 3

- Gemfile.lock
- app/controllers/posts_controller.rb
- app/views/layouts/application.html.erb
- app/views/posts/index.html.erb
- Clean up changes from #71 and #80 
-
-
> Clean up some more code

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/likes.scss
- app/controllers/comments_controller.rb
- app/controllers/likes_controller.rb
- app/controllers/posts_controller.rb
- app/controllers/profiles_controller.rb
- app/helpers/likes_helper.rb
- app/models/comment.rb
- app/models/concerns/likable.rb
- app/models/likable.rb
- app/models/like.rb
- app/models/post.rb
- app/models/user.rb
- app/views/posts/_postbody.html.erb
- app/views/profiles/profile.html.erb
- app/views/shared/_postcard.html.erb
- db/migrate/20191123085738_create_likes.rb
- db/migrate/20191123093559_rename_likes_field_in_post.rb
- db/migrate/20191123093608_add_like_count_to_comment.rb
- db/migrate/20191124102804_drop_votes_table.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/likes_controller_spec.rb
- spec/factories/comments.rb
- spec/factories/likes.rb
- spec/factories/posts.rb
- spec/helpers/likes_helper_spec.rb
- spec/models/like_spec.rb
- spec/models/post_spec.rb
- Get rid of `acts_as_votable` gem in favor of custom reimplementation
- Kept interfaces the same (`liked?`, `liked_by`, etc.) to keep things easier
-
> Reimplement likes

- .eslintrc.json
- app/controllers/comments_controller.rb
- app/controllers/posts_controller.rb
- app/models/comment.rb
- app/models/post.rb
- app/views/comments/_commentbody.html.erb
- app/views/posts/_postbody.html.erb
- app/views/posts/show.html.erb
- app/views/profiles/profile.html.erb
- package.json
- yarn.lock
- Re-add functionality to delete posts/comments
- which will automatically delete associated likes
- Add page for post 404
- Some yarn cleanup
Resolves #96
> Fix deletion of posts and comments

- app/controllers/posts_controller.rb
> Sort comments by spice level

- load_test/loadtest.xml
- Not logged in: 20%
- Logged in: 80%
-
> Re-add Tsung probabilities

- app/controllers/posts_controller.rb
- app/controllers/spiciest_controller.rb
- app/views/posts/_postbody.html.erb
- app/views/posts/index.html.erb
- app/views/spiciest/spiciest.html.erb
- Shortens some code in #101 
-
-
> Pagination cleanup

- db/seeds_real.rb
- 10 usrs * 10 posts + 200 comments
-
-
> Scale back seed size

- db/seeds.rb
> Even smaller

- app/models/concerns/likable.rb
> Fix updated_at timestamp when liking

- db/seeds.rb
- Since we still have lots of 502s...
-
-
> Try no seeding for baseline

- db/seeds.rb
> 2 * 5 + 10

- load_test/loadtest.xml
> EC2 DNS in XML

- app/controllers/profiles_controller.rb
- app/views/profiles/profile.html.erb
> removed loc from profile page

- load_test/loadtest.xml
This reverts commit 4cfeaa9f03cb3e25bfd126e5ca258693d9a2c2c5.
-
-
-
> Revert "Add image to load testing (#111)"

- db/seeds.rb
- Now 25 * 25 + 1250 + 2500
-
-
> Add likes to seeds.rb

- load_test/loadtest.xml
> 30 to 60 for load test

- app/controllers/comments_controller.rb
- app/controllers/posts_controller.rb
- app/views/comments/_commentbody.html.erb
- app/views/comments/destroy.js.erb
- app/views/comments/toggle_like_comment.js.erb
- app/views/posts/_postbody.html.erb
- app/views/posts/toggle_like_post.js.erb
- app/views/shared/_header.html.erb
- app/views/shared/_postcard.html.erb
- load_test/loadtest.xml
- Toggling post and comment likes is AJAX instead of reload
- So is deleting comments (but not adding them)
-
> AJAX-ify likes

- app/controllers/posts_controller.rb
- app/controllers/profiles_controller.rb
- app/controllers/spiciest_controller.rb
- app/models/comment.rb
- app/models/like.rb
- app/models/post.rb
- app/views/comments/_commentbody.html.erb
- app/views/posts/_postbody.html.erb
- app/views/profiles/profile.html.erb
- app/views/shared/_postcard.html.erb
- db/migrate/20191204104441_add_comments_count_to_posts.rb
- db/migrate/20191204115532_add_indices_to_post.rb
- db/migrate/20191205115206_add_counter_cache_to_user.rb
- db/schema.rb
- spec/factories/posts.rb
- spec/models/post_spec.rb
- Lots of eager loading (imgs, posts, comments, etc)
- Change all the `like.count`s to `like_count`
- Add a cache counter for comments count
- Add an index on Post user_id for the profile page
> Begin DB optimizations

- load_test/loadtest.xml
> Accept headers for AJAX likes

- app/controllers/posts_controller.rb
- app/views/posts/_postbody.html.erb
- app/views/posts/index.html.erb
- app/views/posts/show.html.erb
> Session cache PostGIS

- app/controllers/comments_controller.rb
- app/controllers/posts_controller.rb
- app/views/comments/_commentbody.html.erb
- app/views/posts/_postbody.html.erb
> Session cache for likes

- app/controllers/posts_controller.rb
- app/views/posts/_postbody.html.erb
- app/views/shared/_postcard.html.erb
> More bug fixes
